---
# https://snapcraft.io/docs/installing-snap-on-centos
- name: Add EPEL repo 4 CentOS 7\RHEL
  when:
    - ansible_os_family == 'RedHat'
    - ansible_pkg_mgr == 'yum'
  vars:
    # https://stackoverflow.com/a/47091066/5430535
    # https://github.com/ansible/ansible/issues/32532#issuecomment-341641007
    ansible_python_interpreter: /usr/bin/python2.7
  become: yes
  # https://fedoraproject.org/wiki/EPEL
  package:
    name:
      - epel-release
    state: present

- name: Add EPEL repo 4 CentOS 8+\RHEL
  when:
    - ansible_os_family == 'RedHat'
    - ansible_pkg_mgr == 'dnf'
    - ansible_distribution != 'Fedora'
  become: yes
  package:
    name:
      - epel-release
    state: present

- name: Install snapd and config service 4 enterprise RHEL-like
  when:
    - ansible_os_family == 'RedHat'
    - ansible_pkg_mgr == 'yum'
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python2.7
  package:
    name:
      - snapd
    state: present
  notify:
    - start-snapd-socket
