---
# https://snapcraft.io/docs/installing-snap-on-opensuse
- name: Add repo snapd 4 OpenSUSE Tumbleweed
  when:
    - ansible_system == 'Linux'
    - ansible_os_family == 'Suse'
    - ansible_pkg_mgr == 'zypper'
    - ansible_distribution == 'openSUSE Tumbleweed'
  become: yes
  zypper_repository:
    name: system_snappy
    repo: "{{ http_or_https }}://download.opensuse.org/repositories/system:/snappy/{{ ansible_distribution | replace(' ', '_') }}/"
    auto_import_keys: yes
    runrefresh: yes
    state: present

- name: Add repo snapd 4 OpenSUSE Leap
  when:
    - ansible_system == 'Linux'
    - ansible_os_family == 'Suse'
    - ansible_pkg_mgr == 'zypper'
    - ansible_distribution == 'openSUSE Leap'
  become: yes
  zypper_repository:
    name: system_snappy
    repo: "{{ http_or_https }}://download.opensuse.org/repositories/system:/snappy/{{ ansible_distribution | replace(' ', '_') }}_{{ ansible_distribution_version }}/"
    auto_import_keys: yes
    runrefresh: yes
    state: present
